name = "smart-jewellers-saas"
compatibility_date = "2026-09-15"
main = "functions/api/[[route]].ts"

[assets]
directory = "./dist"

[vars]
ENVIRONMENT = "production"
APP_NAME = "Smart Jewellers SaaS"

[[d1_databases]]
binding = "DB"
database_name = "sj_db_prod"
database_id = "9c65c9d6-d560-4c31-b951-3cb20d563e59"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "sj-logos-prod"
